#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Generate C++ and Rust types from the language-neutral protocol/schema/.

This is the M0 generation-tooling smoke path: one schema, both consumers,
checked-in output, and a drift check in CI. C01 extends this generator (or
replaces its type mapping) for the real snapshot contract; the tool's job
--check that generated output matches committed output--stays the same.
"""
import argparse
import pathlib
import sys
import tomllib

CPP_TYPES = {"u32": "uint32_t", "string": "std::string", "bool": "bool"}
RUST_TYPES = {"u32": "u32", "string": "String", "bool": "bool"}

HEADER_NOTE = "Generated by protocol/tools/generate.py from protocol/schema/. Do not edit by hand."


def load_messages(schema_dir: pathlib.Path):
    messages = []
    for schema_file in sorted(schema_dir.glob("*.toml")):
        with schema_file.open("rb") as f:
            doc = tomllib.load(f)
        for message in doc.get("messages", []):
            messages.append((schema_file.name, message))
    return messages


def render_cpp(messages) -> str:
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        f"// {HEADER_NOTE}",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string>",
        "",
        "namespace protocol::generated {",
        "",
    ]
    for source, message in messages:
        lines.append(f"// From {source}")
        lines.append(f"struct {message['name']} {{")
        for field in message["fields"]:
            lines.append(f"  {CPP_TYPES[field['type']]} {field['name']};")
        lines.append("};")
        lines.append("")
    lines.append("}  // namespace protocol::generated")
    lines.append("")
    return "\n".join(lines)


def render_rust(messages) -> str:
    # Rust output feeds host/ (GPL-3.0-only), not the firmware image; only
    # the C++ output above is Apache-2.0 (see CONTRIBUTING.md).
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-only",
        f"// {HEADER_NOTE}",
        "",
    ]
    for source, message in messages:
        lines.append(f"// From {source}")
        lines.append("#[derive(Debug, Clone, PartialEq)]")
        lines.append(f"pub struct {message['name']} {{")
        for field in message["fields"]:
            lines.append(f"    pub {field['name']}: {RUST_TYPES[field['type']]},")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--schema-dir", type=pathlib.Path, required=True)
    parser.add_argument("--cpp-out", type=pathlib.Path, required=True)
    parser.add_argument("--rust-out", type=pathlib.Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if generated output would differ from the existing files",
    )
    args = parser.parse_args()

    messages = load_messages(args.schema_dir)
    cpp_text = render_cpp(messages)
    rust_text = render_rust(messages)

    if args.check:
        ok = True
        for path, text in ((args.cpp_out, cpp_text), (args.rust_out, rust_text)):
            existing = path.read_text() if path.exists() else None
            if existing != text:
                print(f"drift: {path} is out of date; rerun generate.py", file=sys.stderr)
                ok = False
        return 0 if ok else 1

    args.cpp_out.parent.mkdir(parents=True, exist_ok=True)
    args.rust_out.parent.mkdir(parents=True, exist_ok=True)
    args.cpp_out.write_text(cpp_text)
    args.rust_out.write_text(rust_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
